
namespace ObserverDesignPattern
{
    public class Program
    {
        public static void Main(string[] args)
        {
            //this code is mostly generated by chatgpt 3.5
            //I will organize and arrange the code

            // Create stock market
            StockMarket stockMarket = new StockMarket();

            // Create clients which means observers
            StockTrader btcTrader = new StockTrader("Btc Trader");
            StockTrader dolarTrader = new StockTrader("Dolar Trader");
            StockAnalyst analyst = new StockAnalyst("Analyst");

            // Register observers with the stock market
            stockMarket.RegisterObserver(btcTrader);
            stockMarket.RegisterObserver(dolarTrader);
            stockMarket.RegisterObserver(analyst);

            // Simulate receiving new stock prices
            stockMarket.UpdateStockPrice("BTC", 980.0m);
            stockMarket.UpdateStockPrice("DOLAR", 4.0m);

            // Unregister an observer if the trader is no longer interested
            stockMarket.RemoveObserver(dolarTrader);

            // Simulate more stock price updates
            stockMarket.UpdateStockPrice("BTC", 680.0m);
            stockMarket.UpdateStockPrice("DOLAR", 4.5m);
        }
    }
}